@startuml

' Акторы
actor "HR-Менеджер" as Meneger
actor "Программный код" as Program

' Варианты использования


' Варианты использования, которые будут применены как дополнительные.
usecase "Добавлении должности" as Add_D
usecase "Статус" as Status
usecase "Сохраняет бд" as Add
usecase "Система проверяет" as Sys_D


' Связи актёров с вариантами использования
Meneger -- Add_D
Program -- Sys_D
Program -- Add

' Детализация процесса оформления заказа (INCLUDE-связи) - обязательные связи - то что включается в процесс
Add_D --> Status : <<include>>

' EXTEND-связи (опциональные действия) - дополнительные действия, которые могут быть выполнены

@enduml