@startuml

' Акторы
actor "HR-менеджер" as HR_менеджер

' Варианты использования

' Варианты использования, которые будут применены как дополнительные.
usecase "Создать локацию" as US_ES
usecase "Активный или неактивный" as ACT_Unactive
usecase "Временная зона" as Time_Zone

' Связи актёров с вариантами использования
HR_менеджер -- US_ES

' Детализация процесса оформления заказа (INCLUDE-связи) - обязательные связи - то что включается в процесс
US_ES --> Time_Zone : <<include>>

' EXTEND-связи (опциональные действия) - дополнительные действия, которые могут быть выполнены
US_ES <.. ACT_Unactive : <<extend>>

@enduml